trigger: none

pr:
  branches:
    include:
    - "*"

schedules:
- cron: "0 13 * * *" # 1PM UTC => 5 AM PST
  displayName: HttpStress nightly run
  branches:
    include:
    - master

pool:
  name: Hosted Ubuntu 1604

variables:
  - template: ../variables.yml
  - name: dockerfilesFolder
    value: $(Build.SourcesDirectory)/eng/docker
  - name: httpStressProject
    value: $(sourcesRoot)/System.Net.Http/tests/StressTests/HttpStress
  - name: sdkBaseImage
    value: dotnet-sdk-libraries-current
  - name: httpStressImage
    value: httpstress

steps:
- checkout: self
  clean: true
  fetchDepth: 1
  lfs: false

- bash: |
    $(dockerfilesFolder)/build-docker-sdk.ps1 -t $(sdkBaseImage) -c $(BUILD_CONFIGURATION)
  displayName: Build Libraries

- bash: |
    $(httpStressProject)/run-docker-compose.ps1 -o -c $(BUILD_CONFIGURATION) -t $(sdkBaseImage)
  displayName: Build HttpStress

- bash: |
    cd '$(httpStressProject)'
    docker-compose up --abort-on-container-exit --no-color
  displayName: Run HttpStress
  env:
    HTTPSTRESS_IMAGE: $(httpStressImage)
