trigger: none

pr:
  branches:
    include:
    - "*"

schedules:
- cron: "0 13 * * *" # 1PM UTC => 5 AM PST
  displayName: SslStress nightly run
  branches:
    include:
    - master

pool:
  vmImage: 'windows-latest'

variables:
  - template: ../variables.yml
  - name: dockerfilesFolder
    value: $(Build.SourcesDirectory)/eng/docker
  - name: httpStressProject
    value: $(sourcesRoot)/System.Net.Http/tests/StressTests/HttpStress
  - name: sdkBaseImage
    value: dotnet-sdk-libraries-current

steps:
- checkout: self
  clean: true
  fetchDepth: 1
  lfs: false

- pwsh: |
    $(dockerfilesFolder)/build-docker-sdk.ps1 -w -t $(sdkBaseImage) -c $(BUILD_CONFIGURATION)
  displayName: Build Libraries

- pwsh: |
    $(sslStressProject)/run-docker-compose.ps1 -w -o -c $(BUILD_CONFIGURATION) -t $(sdkBaseImage)
  displayName: Build SslStress

- pwsh: |
    cd '$(sslStressProject)'
    docker-compose up --abort-on-container-exit --no-color
  displayName: Run SslStress

- task: PublishBuildArtifacts@1
  displayName: Publish Logs
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/artifacts/log/$(BUILD_CONFIGURATION)'
    PublishLocation: Container
    ArtifactName: 'sslstress_$(Agent.Os)_$(Agent.JobName)'
  continueOnError: true
  condition: always()
