trigger: none

pr:
  branches:
    include:
    - "*"

schedules:
- cron: "0 13 * * *" # 1PM UTC => 5 AM PST
  displayName: SslStress nightly run
  branches:
    include:
    - master

pool:
  name: Hosted Ubuntu 1604

variables:
  - template: ../variables.yml
  - name: dockerfilesFolder
    value: $(Build.SourcesDirectory)/eng/docker
  - name: sslStressProject
    value: $(sourcesRoot)/System.Net.Security/tests/StressTests/SslStress
  - name: sdkBaseImage
    value: dotnet-sdk-libraries-current
  - name: sslStressImage
    value: sslstress

steps:
- checkout: self
  clean: true
  fetchDepth: 1
  lfs: false

- bash: |
    export CONFIGURATION=$(BUILD_CONFIGURATION)
    export DOCKER_IMAGE_TAG=$(sdkBaseImage)
    $(dockerfilesFolder)/build-docker-sdk.sh
  displayName: Build Libraries

- bash: |
    # we need to include the entire src/libraries folder in the build context due to Common/ dependencies
    docker build -t $(sslStressImage) --build-arg SDK_BASE_IMAGE=$(sdkBaseImage) --build-arg CONFIGURATION=$(BUILD_CONFIGURATION) -f $(sslStressProject)/Dockerfile src/libraries
  displayName: Build SslStress

- bash: |
    cd '$(sslStressProject)'
    docker-compose up --abort-on-container-exit --no-color
  displayName: Run SslStress
  env:
    SSLSTRESS_IMAGE: $(sslStressImage)
