trigger: none

pr:
  branches:
    include:
    - "*"

schedules:
- cron: "0 13 * * *" # 1PM UTC => 5 AM PST
  displayName: SslStress nightly run
  branches:
    include:
    - master

pool:
  name: Hosted Ubuntu 1604

variables:
  - template: ../variables.yml
  - name: dockerfilesFolder
    value: $(Build.SourcesDirectory)/eng/docker
  - name: sslStressProject
    value: $(sourcesRoot)/System.Net.Security/tests/StressTests/SslStress
  - name: sdkBaseImage
    value: dotnet-sdk-libraries-current

steps:
- checkout: self
  clean: true
  fetchDepth: 1
  lfs: false

- bash: |
    $(dockerfilesFolder)/build-docker-sdk.ps1 -t $(sdkBaseImage) -c $(BUILD_CONFIGURATION)
  displayName: Build Libraries

- bash: |
    $(sslStressProject)/run-docker-compose.ps1 -o -c $(BUILD_CONFIGURATION) -t $(sdkBaseImage)
  displayName: Build SslStress

- bash: |
    cd '$(sslStressProject)'
    docker-compose up --abort-on-container-exit --no-color
  displayName: Run SslStress
